library(dplyr)
library(ggplot2)

# NOTE: The "aggregated_results.rda" file is not included in this repository.
# It is the output generated by 04_aggregate_results.R.
load("aggregated_results.rda")

# --- Create a custom theme object to reuse for all plots ---
my_plot_theme <- theme(
  plot.title = element_text(hjust = 0.5, size = 14),
  legend.title = element_text(size = 14),
  legend.text = element_text(size = 12),
  axis.title = element_text(size = 14),
  axis.text.x = element_text(size = 14),
  axis.line.x = element_line(size = 1),
  axis.text.y = element_text(size = 14),
  axis.line.y = element_line(size = 1),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  panel.background = element_blank(),
  axis.line = element_line(colour = "black")
)

# --- Median Performance Plots ---

summsumm_median <- summ %>%
  group_by(NT, NW, Ratio) %>%
  summarize(Time = median(Time))

# To-do list plot (Median)
ggplot(filter(summsumm_median, NW == 10), aes(x = Ratio, y = Time, color = factor(NT))) +
  geom_line(size = 1.2) +
  labs(title= '"To-do list" selection', color = "Number of tasks", x = "Ratio", y = "Group performance") +
  my_plot_theme +
  guides(colour = guide_legend(reverse=T))

# Blind selection plot (Median)
ggplot(filter(summsumm_median, NW == 10), aes(x = Ratio, y = Time, color = factor(NT))) +
  geom_line(size = 1.2) +
  labs(title= '"Blind" selection', color = "Number of tasks", x = "Ratio", y = "Group performance") +
  my_plot_theme +
  guides(colour = guide_legend(reverse=T))


# --- Performance Dispersion Plots ---

summsumm_iqr <- summ %>%
  group_by(NT, NW, Ratio) %>%
  summarize(Time = IQR(Time))

# To-do list plot (IQR)
ggplot(filter(summsumm_iqr, NW == 10), aes(x = Ratio, y = Time, color = factor(NT))) +
  geom_line(size = 1.2) +
  labs(title= '"To-do list" selection', color = "Number of tasks", x = "Ratio", y = "Group performance") +
  my_plot_theme +
  guides(colour = guide_legend(reverse=T))

# Blind selection plot (IQR)
ggplot(filter(summsumm_iqr, NW == 10), aes(x = Ratio, y = Time, color = factor(NT))) +
  geom_line(size = 1.2) +
  labs(title= '"Blind" selection', color = "Number of tasks", x = "Ratio", y = "Group performance") +
  my_plot_theme +
  guides(colour = guide_legend(reverse=T))